### ISSUE TITLE
color pre-trained model

### ISSUE THREAD

**Issue by amirhamidihd** [majedelhelou/SFM#5]
Hi, 
could you upload a pre-trained model for color images?
Thanks

**Comment by majedelhelou** [comment]
Hello, for which experiment? The SR networks are trained for color images, and in denoising the real-image experiments are over 3 channels but the AWGN is over grayscale. AWGN removal is a fundamental theoretical task, its importance is more from a theoretical point of view rather than applied (where noise is not simply Gaussian), and with color images there is significant correlation across channels that makes the AWGN removal problem much easier (due to the inter-channel correlations -[discussed here](https://doi.org/10.1109/ICIP.2017.8296512)- the problem becomes more like joint AWGN & burst-fusion denoising). That is why most papers that address it present results over grayscale images, and we do not conduct those experiments on color images.
Let us know if you have any further questions!

**Comment by amirhamidihd** [comment]
Thanks for your reply,
I want to use the SFM denoising part, for the denoising tasks.
my input images have 3 RGB channels, I have seen only gray pre-trained models on your Github in Denoising/Saved_models part, 
how can I use the denoising part with RGB images?

**Comment by majedelhelou** [comment]
Hello
For RGB you would need to train your own model, as we did not study AWGN removal on RGB data for the reasons mentioned above, so there are no pre-trained models in this repo. Alternatively, you could just pass the RGB channels one by one to the grayscale model, but this would probably result in weaker performance.
The `random_drop` function in [utils_SFM](https://github.com/majedelhelou/SFM/blob/master/Denoising/utils_SFM.py) is implemented to already support 3-channel masking, so you can use that directly for applying SFM on RGB images for your project!
Hope this helps.

**Comment by JackeyDeng** [comment]
aaa
